# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20160528_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssinput',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 28, 22, 43, 40, 558976, tzinfo=utc), verbose_name='date published'),
        ),
    ]
