# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20160529_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeedBulk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('href', models.CharField(max_length=350)),
                ('author', models.CharField(max_length=150)),
                ('img_src', models.CharField(max_length=350)),
            ],
        ),
    ]
