# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_rssfeedbulk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeedbulk',
            name='category',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
